export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO";
export const CART_CLEAR_ITEMS = "CART_CLEAR_ITEMS";
export const PLUS_QUANTITY = "PLUS_QUANTITY";
export const MINUS_QUANTITY = "MINUS_QUANTITY";
